---
- name: Configure enforcing of TLS
  ldap_attrs:
    server_uri: "{{ dirsrv_server_uri }}"
    validate_certs: "{{ dirsrv_tls_certificate_trusted }}"
    start_tls: "{{ dirsrv_starttls_early }}"
    bind_dn: "{{ dirsrv_rootdn }}"
    bind_pw: "{{ dirsrv_rootdn_password }}"
    dn: "cn=config"
    attributes:
      nsslapd-require-secure-binds: "{{ (dirsrv_tls_enabled and dirsrv_tls_enforced) | bool | ternary('on', 'off') }}"
      nsslapd-minssf: "{{ (dirsrv_tls_enabled and dirsrv_tls_enforced) | bool | ternary(dirsrv_tls_minssf, '0') }}"
      nsslapd-localssf: "{{ (dirsrv_tls_enabled and dirsrv_tls_enforced) | bool | ternary(dirsrv_tls_minssf, '0') }}"
    state: exact
  tags: [ dirsrv_tls ]
  register: dirsrv_restart_condition_tls_enforcing_1
